name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2 with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list sudo apt-get update sudo apt-get install -y google-chrome-stable
      - name: Start SUT run: java -jar ./artifacts/app-mbank.jar &
      - name: Wait for SUT to be available run: |
          for i in {1..10}; do if curl -s http://localhost:9999; then echo "SUT is up!"
              break
            fi
            echo "Waiting for SUT to start..."
            sleep 5
          done
      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true
